name: demo
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          wget http://www.ehu.eus/ccwintco/uploads/6/67/Indian_pines_corrected.mat -O datasets/Indian_pines_corrected.mat
          wget http://www.ehu.eus/ccwintco/uploads/c/c4/Indian_pines_gt.mat -O datasets/Indian_pines_gt.mat
          git checkout demo
          cd SSRN
          python indian.py

          # Write your CML report
          cat records/pca_indian.txt_IN_25_0.8.txt >> report.md
          cml-send-comment report.md
